all:
  children:
    prd:
      vars:
        ansible_user: taira
        ansible_ssh_private_key_file: /home/{{ ansible_user }}/.ssh/id_rsa
      children:
        controllers:
          hosts:
            nucos01:
              ansible_host: 10.234.14.11
        workers:
          hosts:
            nucos02:
              ansible_host: 10.234.14.12
            # nucos03:
            #   ansible_host: 10.234.14.13
