- name: task内の変数を定義します。
  set_fact:
    task_file: both-password.yaml
    service_name: password

- name: "{{ task_file }} Set passwords for development"
  set_fact:
    PW_MARIADB: "{{ lookup('env', 'DEV_PW_MARIADB') }}"
    PW_RABBITMQ: "{{ lookup('env', 'DEV_PW_RABBITMQ') }}"
    PW_OS_ADMIN: "{{ lookup('env', 'DEV_PW_OS_ADMIN') }}"
    PW_OS_KEYSTONE: "{{ lookup('env', 'DEV_PW_OS_KEYSTONE') }}"
    PW_OS_GLANCE: "{{ lookup('env', 'DEV_PW_OS_GLANCE') }}"
    PW_OS_PLACEMENT: "{{ lookup('env', 'DEV_PW_OS_PLACEMENT') }}"
    PW_OS_CINDER: "{{ lookup('env', 'DEV_PW_OS_CINDER') }}"
    PW_OS_NOVA: "{{ lookup('env', 'DEV_PW_OS_NOVA') }}"
    PW_OS_NEUTRON: "{{ lookup('env', 'DEV_PW_OS_NEUTRON') }}"
    PW_OS_METADATA: "{{ lookup('env', 'DEV_PW_OS_METADATA') }}"
    PW_OS_ADD_NAME: "{{ lookup('env', 'DEV_PW_OS_ADD_NAME') }}"
  when: env == "dev"

- name: "{{ task_file }} Set passwords for production"
  set_fact:
    PW_MARIADB: "{{ lookup('env', 'PRD_PW_MARIADB') }}"
    PW_RABBITMQ: "{{ lookup('env', 'PRD_PW_RABBITMQ') }}"
    PW_OS_ADMIN: "{{ lookup('env', 'PRD_PW_OS_ADMIN') }}"
    PW_OS_KEYSTONE: "{{ lookup('env', 'PRD_PW_OS_KEYSTONE') }}"
    PW_OS_GLANCE: "{{ lookup('env', 'PRD_PW_OS_GLANCE') }}"
    PW_OS_PLACEMENT: "{{ lookup('env', 'PRD_PW_OS_PLACEMENT') }}"
    PW_OS_CINDER: "{{ lookup('env', 'PRD_PW_OS_CINDER') }}"
    PW_OS_NOVA: "{{ lookup('env', 'PRD_PW_OS_NOVA') }}"
    PW_OS_NEUTRON: "{{ lookup('env', 'PRD_PW_OS_NEUTRON') }}"
    PW_OS_METADATA: "{{ lookup('env', 'PRD_PW_OS_METADATA') }}"
    PW_OS_ADD_NAME: "{{ lookup('env', 'PRD_PW_OS_ADD_NAME') }}"
  when: env == "prd"
