- name: task内の変数を定義します。
  set_fact:
    task_file: mariadb.yaml
    service_name: mariadb
    eth0_ip: "{{ ansible_default_ipv4.address }}"

- name: "{{ task_file }} 各種パッケージを追加します。"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - python3-pymysql
    - expect

- name: "{{ task_file }} 初期ファイルを削除します。"
  file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    state: absent

- name: "{{ task_file }} 99-openstack.cnf を用意します。"
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    mode: 0644
    force: yes
  register: mariadb_config
  when:
    - not ansible_check_mode

- name: "{{ task_file }} 再起動し永続化します。"
  systemd:
    name: mysql
    state: restarted
    enabled: yes
  when:
    - mariadb_config.changed
    - not ansible_check_mode

- name: "{{ task_file }} rootパスワードを更新します。"
  mysql_user:
    login_user: root                   # login時のユーザー名
    login_password: "{{ PW_MARIADB }}" # login時のパスワード
    name: root                         # 変更対象のユーザー名
    password: "{{ PW_MARIADB }}"       # 変更対象の新しいパスワード
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /run/mysqld/mysqld.sock
  when: not ansible_check_mode

- name: "{{ task_file }} anonymousユーザーを削除します"
  mysql_user:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: ''
    host: "%"
    state: absent
  when: not ansible_check_mode

- name: "{{ task_file }} リモートからのrootログインを拒否します"
  mysql_user:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: root
    host: "%"
    state: absent
  when: not ansible_check_mode

- name: "{{ task_file }} テストデータベースを削除します"
  mysql_db:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: test
    state: absent
  when: not ansible_check_mode

- name: "{{ task_file }} ローカルからのrootログインを許可します"
  mysql_user:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: root
    password: "{{ PW_MARIADB }}"
    priv: '*.*:ALL,GRANT'
  when: not ansible_check_mode

- name: "{{ task_file }} 権限テーブルを読み込みし直します"
  command: mysql -u root -p"{{ PW_MARIADB }}" -e "FLUSH PRIVILEGES"
  when: not ansible_check_mode
