- name: task内の変数を定義します。
  set_fact:
    task_file: os-keystone.yaml
    service_name: keystone
    check_table: user
    env_vars:
      OS_USERNAME: "{{ OS_USERNAME }}"
      OS_PASSWORD: "{{ OS_PASSWORD }}"
      OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
      OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
      OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
      OS_AUTH_URL: "{{ OS_AUTH_URL }}"
      OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
      OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"

- name: "{{ task_file }} {{ check_table }} テーブルがあるか確認します。"
  command: mysql -u root -p'{{ PW_MARIADB }}' -e "USE keystone; SHOW TABLES LIKE '{{ check_table }}';"
  register: db_check_result
  ignore_errors: true

- name: "{{ task_file }} debug テーブルの確認結果を表示"
  debug:
    msg:
      - "RC: {{ db_check_result.rc }}"
      - "stdout_lines: {{ db_check_result.stdout_lines }}"

- name: "{{ task_file }} DBを作成します。"
  mysql_db:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: keystone
    state: present
  when:
    - "'user' not in db_check_result.stdout"
    - not ansible_check_mode

- name: "{{ task_file }} localhost用のユーザーを追加します。"
  mysql_user:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: keystone
    password: "{{ PW_OS_KEYSTONE }}"
    priv: 'keystone.*:ALL'
    host: localhost
    state: present
  when:
    - "'user' not in db_check_result.stdout"
    - not ansible_check_mode

- name: "{{ task_file }} 全ホスト用のユーザーを追加します。"
  mysql_user:
    login_user: root
    login_password: "{{ PW_MARIADB }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: keystone
    password: "{{ PW_OS_KEYSTONE }}"
    priv: 'keystone.*:ALL'
    host: "%"
    state: present
  when:
    - "'user' not in db_check_result.stdout"
    - not ansible_check_mode

- name: "{{ task_file }} 各種パッケージを追加します。"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - keystone

- name: "{{ task_file }} keystone.conf を用意します。"
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    mode: 0644
    force: yes

- name: "{{ task_file }} DBのマイグレーションを行います。"
  command: "/usr/bin/keystone-manage db_sync"
  become_method: sudo
  become_user: keystone
  when:
    - "'user' not in db_check_result.stdout"
    - not ansible_check_mode

- name: "{{ task_file }} fernet keysがあるか確認します。"
  stat:
    path: "/etc/keystone/fernet-keys/0"
  register: fernet_keys_check_result

- name: "{{ task_file }} fernetトークンの初期化を行います。"
  command: "{{ item }}"
  with_items:
    - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  when: not fernet_keys_check_result.stat.exists

- name: "{{ task_file }} credential keysがあるか確認します。"
  stat:
    path: "/etc/keystone/credential-keys/0"
  register: credential_keys_check_result

- name: "{{ task_file }} credentialの作成を行います。"
  command: "{{ item }}"
  with_items:
    - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  when: not credential_keys_check_result.stat.exists

- name: "{{ task_file }} エンドポイントが既にあるか確認します。"
  shell: openstack endpoint list --service keystone --interface internal
  environment: "{{ env_vars }}"
  register: openstack_endpoint
  ignore_errors: true

- name: "{{ task_file }} エンドポイントの確認結果を表示"
  debug:
    msg:
      - "RC: {{ openstack_endpoint.rc }}"
      - "stdout_lines: {{ openstack_endpoint.stdout_lines }}"

- name: "{{ task_file }} エンドポイントを作成します。"
  command: >
    keystone-manage bootstrap --bootstrap-password {{ PW_OS_ADMIN }}
    --bootstrap-admin-url {{ OS_AUTH_URL }}
    --bootstrap-internal-url {{ OS_AUTH_URL }}
    --bootstrap-public-url {{ OS_AUTH_URL }}
    --bootstrap-region-id {{ region }}
  when: openstack_endpoint.rc != 0 and not openstack_endpoint.stdout_lines

- name: "{{ task_file }} サーバー名をapache2.confで設定します。"
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: 'ServerName {{ ansible_hostname }}.{{ domain }}'
    state: present
  register: apache_config
  when:
    - not ansible_check_mode

- name: "{{ task_file }} apache2をRestartさせます。"
  systemd:
    name: apache2
    state: restarted
    daemon_reload: yes
    enabled: yes
  when:
    - apache_config.changed
    - not ansible_check_mode

- name: "{{ task_file }} Apacheが起動するのを待ちます。"
  wait_for:
    host: "localhost"
    port: 5000
    state: started
    delay: 2  # ポートが開くのを待つ間隔（秒）
    timeout: 300  # 最大待機時間（秒）
  when:
    - not ansible_check_mode

- name: "{{ task_file }} Apacheにアクセスしてみます。"
  uri:
    url: http://localhost:5000/v3/
    return_content: yes
  when:
    - not ansible_check_mode

- name: "{{ task_file }} 各種サービスが所属するserviceプロジェクトを確認します。"
  shell: openstack project show service
  environment: "{{ env_vars }}"
  register: project_check_result
  ignore_errors: true

- name: "{{ task_file }} serviceプロジェクトの確認結果を表示"
  debug:
    msg:
      - "RC: {{ project_check_result.rc }}"
      - "stdout_lines: {{ project_check_result.stdout_lines }}"

- name: "{{ task_file }} 各種サービスが所属するserviceプロジェクトを作成します。"
  shell: openstack project create --domain default --description "Service Project" service
  environment: "{{ env_vars }}"
  when: project_check_result.rc != 0 and not project_check_result.stdout_lines

- name: "{{ task_file }} service-token用のserviceロールを確認します。"
  shell: openstack role show service
  environment: "{{ env_vars }}"
  register: role_check_result
  ignore_errors: true

- name: "{{ task_file }} serviceロールの確認結果を表示"
  debug:
    msg:
      - "RC: {{ role_check_result.rc }}"
      - "stdout_lines: {{ role_check_result.stdout_lines }}"

- name: "{{ task_file }} service-token用のserviceロールを作成します。"
  shell: openstack role create service
  environment: "{{ env_vars }}"
  when: role_check_result.rc != 0 and not role_check_result.stdout_lines

