- name: task内の変数を定義します。
  set_fact:
    task_file: rabbitmq.yaml
    service_name: rabbitmq

- name: "{{ task_file }} 各種パッケージを追加します。"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - rabbitmq-server

- name: "{{ task_file }} RabbitMQユーザーリストを取得します。"
  command: rabbitmqctl list_users
  register: rabbitmq_users
  changed_when: False

- name: "{{ task_file }} openstackユーザーを作成します。"
  command: rabbitmqctl add_user openstack {{ PW_RABBITMQ }}
  # 結果をrabbitmq_add_user_resultにキャッシュさせます。
  register: rabbitmq_add_user_result
  # コマンドの実行が失敗したときにエラーとして処理します。
  failed_when : rabbitmq_add_user_result.rc !=0
  when: "'openstack' not in rabbitmq_users.stdout"

# 1度設定した後は以下のように権限を確認できます。これを利用して2回実行しないようにしています。
# ```
# Listing permissions for user "openstack" ...
# vhost   configure       write   read
# /       .*      .*      .*
# ```

- name: "{{ task_file }} openstackユーザーの権限を確認します。"
  shell: rabbitmqctl list_user_permissions openstack | grep -P "^/\s+\.\*\s+\.\*\s+\.\*$"
  register: rabbitmq_user_permissions
  failed_when: false
  changed_when: false

- name: "{{ task_file }} openstackユーザーにフル権限を与えます。"
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  register: rabbitmq_permissions_result
  when: rabbitmq_user_permissions.rc != 0

- name: "{{ task_file }} Restartさせます。"
  systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes
    enabled: yes
  when:
    - rabbitmq_add_user_result.changed or rabbitmq_permissions_result.changed
    - not ansible_check_mode