all:
  children:
    dev:                                 # devかprdを選択します。
      vars:
        ansible_user: taira              # ansibleで接続するユーザー名を指定します。
        ansible_ssh_private_key_file: /home/{{ ansible_user }}/.ssh/id_rsa # ansibleで接続する秘密鍵のパスを指定します。
      children:
        controllers:                     # コントローラーグループ名。この名前は変更しないでください。
          hosts:
            pios01:
              ansible_host: 10.234.15.11 # ホスト名はRPi imagerで設定したもので、ドメインを含めずに記述してください。
        workers:                         # ワーカーグループ名。この名前は変更しないでください。
          hosts:
            pios02:                      # 1台目のワーカーです。
              ansible_host: 10.234.15.12
            # pios03:                      # ワーカーが複数台ある場合は、このように記述してください。
            #   ansible_host: 10.234.15.13
